version: "3.7"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: inventory
      POSTGRES_PASSWORD: inventory-development
    ports:
      - 5432:5432
  backend:
    build:
      context: ../../
      dockerfile: deployments/development/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../../backend/src:/inventory/src
