version: "3"

services:
  inventory_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: inventory
      POSTGRES_PASSWORD: inventory-development
    ports:
      - 5432:5432
