name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build frontend
      run: "(cd frontend; yarn && yarn build)"

    - name: Run test database in docker
      run: docker-compose -f deployments/testing/docker-compose.yml up -d inventory_database
    - name: Initialize test database
      run: docker-compose -f deployments/testing/docker-compose.yml up inventory_database_initialization
    - name: Run tests
      run: docker-compose -f deployments/testing/docker-compose.yml up inventory_backend_tests
