name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: sudo apt-get install libpq-dev
    - name: Build
      run: cargo build --manifest-path=backend/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path=backend/Cargo.toml --verbose
